<a href="https://colab.research.google.com/github/iplaycos1-crypto/MBA6636/blob/main/Copy_of_MBA6636_3769291_Sun_DEA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment1 with R code by Lei Sun
## Business Problem
### The professor faces a problem when he purchase a diamond for his girl-friend. As a common consumer, he finds it difficult to make choice and evaluate the value. Therefore he collected all diamond pricing data from three wholesalers. The objective is to identify a high-quality diamond at a reasonable price.

In [19]:
install.packages("tidyverse","readxl")

Warning message in install.packages("tidyverse", "readxl"):
“'lib = "readxl"' is not writable”

ERROR: Error in install.packages("tidyverse", "readxl"): unable to install packages

In [18]:
library(tidyverse)
library(readxl)

In [3]:
# GitHub raw file link
data_url <- "https://raw.githubusercontent.com/iplaycos1-crypto/MBA6636/main/Professor_Proposes_Data.xlsx"

In [4]:
# Download the Excel file from My GitHub account
download.file(
  url = data_url,
  destfile = "Professor_Proposes_Data.xlsx",
  mode = "wb"
)

In [5]:
# Read the downloaded file
diamonds_data <- readxl::read_excel(
  path = "Professor_Proposes_Data.xlsx",
  sheet = "Data"
)

In [6]:
head(diamonds_data)

  Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
1 0.92  I      SI2     G   AGS           V      V        3000  1
2 0.92  I      SI2     V   AGS           G      G        3000  1
3 0.82  F      SI2     I   GIA           X      X        3004  1
4 0.81  G      SI1     I   GIA           X      V        3004  1
5 0.90  J      VS2     V   GIA           V      V        3006  1
6 0.87  F      SI2     I   AGS           G      V        3007  1

In [7]:
diamonds_original <- diamonds_data    # keep the original data

In [8]:
diamonds_clean <- diamonds_data       # data after clean

## ---1: Understanding the Data---
### Inspect data quality and clean the data

In [9]:
dim(diamonds_data)

[1] 440   9

In [10]:
# 1. Number of observations (rows)
nrow(diamonds_data)

# 2. Number of variables (columns)
ncol(diamonds_data)

# 3. Display variable names and data types
str(diamonds_data)

[1] 440

[1] 9

tibble [440 × 9] (S3: tbl_df/tbl/data.frame)
 $ Carat        : num [1:440] 0.92 0.92 0.82 0.81 0.9 0.87 0.8 0.84 0.8 0.8 ...
 $ Colour       : chr [1:440] "I" "I" "F" "G" ...
 $ Clarity      : chr [1:440] "SI2" "SI2" "SI2" "SI1" ...
 $ Cut          : chr [1:440] "G" "V" "I" "I" ...
 $ Certification: chr [1:440] "AGS" "AGS" "GIA" "GIA" ...
 $ Polish       : chr [1:440] "V" "G" "X" "X" ...
 $ Symmetry     : chr [1:440] "V" "G" "X" "V" ...
 $ Price        : num [1:440] 3000 3000 3004 3004 3006 ...
 $ Wholesaler   : num [1:440] 1 1 1 1 1 1 1 1 1 1 ...

In [11]:
colSums(is.na(diamonds_clean))    # check missing values

        Carat        Colour       Clarity           Cut Certification
            0             0             0             0             0
       Polish      Symmetry         Price    Wholesaler
            0             0             0             0

In [12]:
sum(duplicated(diamonds_clean))  #count fully duplicated rows

[1] 51

#### *Two diamonds may have identical recorded characteristics and prices but still be separate legitimate observations. A duplicated row is a reason to investigate, not automatic proof of a data-entry error*

In [13]:
diamonds_clean[duplicated(diamonds_clean), ]

   Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
1  0.80  I      VS1     I   AGS           I      I        3031  1
2  1.01  J      SI2     X   EGL           V      V        3139  2
3  1.01  J      SI2     X   EGL           V      V        3139  2
4  1.01  J      SI2     I   EGL           V      X        3139  2
5  0.22  F      SI1     V   IGI           G      G         330  3
6  0.23  F      SI1     X   IGI           G      G         360  3
7  0.28  E      VVS2    X   GIA           V      X         658  3
8  0.30  H      SI2     X   GIA           V      V         493  3
9  0.30  H      SI2     X   GIA           V      V         493  3
10 0.30  H      SI2     X   GIA           V      V         493  3
11 0.30  J      VS2     V   GIA           V      V         493  3
12 0.30  J      VS2     X   GIA           V      V         493  3
13 0.30  F      SI2     V   GIA           V      V         520  3
14 0.30  F      SI2     I   GIA           V      V         520  3
15 0.30  F      SI2     I   GIA           V      V         520  3
16 0.30  F      SI2     V   GIA           V      V         520  3
17 0.30  F      SI2     V   GIA           V      V         520  3
18 0.30  G      SI2     I   GIA           V      V         520  3
19 0.30  G      SI2     X   GIA           V      V         520  3
20 0.30  I      SI1     V   GIA           V      V         520  3
21 0.30  I      SI1     V   GIA           V      V         520  3
22 0.30  I      SI1     V   GIA           V      V         520  3
23 0.30  I      SI1     I   GIA           V      V         520  3
24 0.30  I      SI1     I   GIA           V      V         520  3
25 0.30  I      SI1     V   GIA           V      V         520  3
26 0.30  J      VS1     V   GIA           V      V         520  3
27 0.30  J      VS1     X   GIA           V      V         520  3
28 0.30  J      VS1     V   GIA           V      V         520  3
29 0.30  J      VS1     X   GIA           V      V         520  3
30 0.30  J      VS1     X   GIA           V      V         520  3
31 0.30  J      VS1     V   GIA           V      V         520  3
32 0.30  H      SI1     V   GIA           V      G         547  3
33 0.30  H      SI1     X   GIA           V      V         547  3
34 0.30  H      SI1     X   GIA           G      G         547  3
35 0.30  H      SI1     V   GIA           X      V         547  3
36 0.30  H      SI1     V   GIA           V      V         547  3
37 0.30  H      SI1     X   GIA           V      V         547  3
38 0.30  H      SI1     V   GIA           X      V         547  3
39 0.30  H      SI1     V   GIA           V      V         547  3
40 0.30  H      SI1     V   GIA           X      V         547  3
41 0.30  H      SI1     X   GIA           V      V         547  3
42 0.30  H      SI1     X   GIA           V      V         547  3
43 0.30  H      SI1     X   GIA           V      V         547  3
44 0.30  H      SI1     V   GIA           X      V         547  3
45 0.30  H      SI1     X   GIA           V      V         547  3
46 0.30  I      VS2     I   GIA           V      V         547  3
47 0.30  I      VS2     X   GIA           V      V         547  3
48 0.30  I      VS2     X   GIA           X      V         547  3
49 0.30  I      VS2     I   GIA           G      V         547  3
50 0.30  I      VS2     I   GIA           X      V         547  3
51 0.30  I      VS2     I   GIA           X      V         547  3

In [21]:
categorical_vars <- c(
  "Colour", "Clarity", "Cut",
  "Certification", "Polish",
  "Symmetry", "Wholesaler"
)

lapply(diamonds_clean[categorical_vars], unique)      #

$Colour
[1] "I" "F" "G" "J" "D" "H" "E" "L" "K"

$Clarity
[1] "SI2"  "SI1"  "VS2"  "VS1"  "SI3"  "I2"   "I1"   "VVS2" "VVS1"

$Cut
[1] "G" "V" "I" "F" "X"

$Certification
[1] "AGS" "GIA" "EGL" "DOW" "IGI"

$Polish
[1] "V" "G" "X" "I" "v" "F"

$Symmetry
[1] "V" "G" "X" "I" "F"

$Wholesaler
[1] 1 2 3

In [20]:
summary(diamonds_clean$Carat)
summary(diamonds_clean$Price)

# Inspect potentially invalid observations
diamonds_clean %>%
  filter(
    is.na(Carat) | is.na(Price) |
      Carat <= 0 | Price <= 0
  )

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.0900  0.3000  0.8100  0.6693  1.0100  1.5800

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
    160     520    2169    1717    3012    3145

     Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler